name: $(date:yyyy.MM.dd)$(rev:.r)

schedules:
- cron: '0 6 * * *'
  displayName: 'Daily 6AM Test Run'
  branches:
    include:
    - main

trigger:
  batch: true
  branches: 
    include: 
      - main
  paths:
    include:
      - /Innovian.Telnyx.Storage
      - /Innovian.Telnyx.Storage.Tests

pool: AzureBuildServers

variables:
  - name: BuildNumber
    value: $(Build.BuildNumber)
  - name: ProjectName
    value: Innovian.Telnyx.Storage

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet tool'
  inputs:
   checkLatest:  true
   versionSpec: '>=6.7.0' # Latest versions at https://dist.nuget.org/tools.json
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/$(ProjectName).csproj'
    feedsToUse: 'select'
    vstsFeed: '4d1432f3-ac87-4104-a03a-bc658b00a9ea/0fb21d1f-6c0f-493f-9532-64eeda958e26'
    noCache: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/$(ProjectName).Tests.csproj'
  env:
    Telnyx_ApiKey: $(TelnyxApiKey)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
  inputs:
    command: 'build'
    projects: '**/$(ProjectName).csproj'
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
  inputs:
    command: 'pack'
    packagesToPack: '**/$(ProjectName).csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BuildNumber'

- task: PowerShell@2
  displayName: 'push to NuGet.org'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
  inputs:
    targetType: 'inline'
    script: 'nuget push "$(Build.ArtifactStagingDirectory)\*.nupkg" -ApiKey $(NuGetApiKey) -Source https://api.nuget.org/v3/index.json'
  env:
    NuGetApiKey: $(NuGetApiKey)